### ISSUE TITLE
need a formatted error printer that prints with one call to `write()`

### ISSUE THREAD

**Issue by sophiakoulen** [sophiakoulen/minishell#1]
We need some kind of error printer like:
`print_err("%s: command not found", command")`;
It needs to print the whole line with only one call to `write()`, else we might have problems with multiple processes reading to stderr at the same time and output getting mixed.

**Comment by znichola** [comment]
Yes, I this is a great idea. shouldn't be too difficult. Only need to take care not to leak the malloced string. Maybe we have a fixed butter size? or idk.

**Comment by sophiakoulen** [comment]
Fixed with 488a528d3a243889a9dffa9a6f0d2f67400f712f
