### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by sophiakoulen** [sophiakoulen/minishell#114]
Stop tokenizing at hashtag

**Comment by znichola** [comment]
This line should be modified to include a `|| *str == '#'`, and like you pointed out, while we're at it we can remove the redundant CRFL check as it's triggered on a `\n` and `\r` is white space that will get trimmed. 
```C
// line 30 in tokenizer.c
if (*str == '\0' || *str == '\n' || (*str == '\r' && *str + 1 == '\n'))
return (e_end);
```
