### ISSUE TITLE
shout -n prints the '-N' too

### ISSUE THREAD

**Issue by sophiakoulen** [sophiakoulen/minishell#147]

**Comment by znichola** [comment]
I think we should make the echo get option code a general function, it's basically copypasted for the ast print and would come in handy for this. 

Also I was thinking that it might be a nice idea to have shout treat the string and send over the modified version to echo, this way we also minimise the duplication.

**Comment by sophiakoulen** [comment]
fixed with 66ea1ac1268b3014a71570f97c0a51272c7ae0d2
