### ISSUE TITLE
struct code unification

### ISSUE THREAD

**Issue by znichola** [sophiakoulen/minishell#28]
Each `struct` has `factory` function, eventually it will need a function to `free` the `struct`, and possibly some might need code to `print` the `struct`...

This is kinda starting to resemble a class no? 

I propose we unify the location of all these function like so:

```
structs/
    struct_factory.c
    struct_free.c
    struct_print.c
```

and further more I think maybe it's a good idea to put the function declarations in the same header where the relevant `struct` is defined. I know contrary to what I said earlier today, but really this is info that's useful while your looking at the `struct` definition.

**Comment by sophiakoulen** [comment]
Are you proposing to do this for all structures in minishell or only for parsing?
I'm afraid unifiying all structures this way might make reading our project less intuitive.
We should separate structures used only for parsing and structures used only for execution.

**Comment by sophiakoulen** [comment]
I do agree with the fact that it is a great idea to systematically write a printer for each structure.
I'm used to write code that frees stuff in the form `cleanup_thing.c`, do you prefer `thing_free.c`?

**Comment by znichola** [comment]
I propose this for all structs. I don't see this the token_factory code belongs to in tokenization as it's used all over the place in parsing, and code to print it can also be used anywhere. To me it makes sense for these kind of utility functions to be in one place. 

Much like how class definitions and class methods are separated from the rest of the function in C++ or an object oriented languages. This code is not specific to one step but rather to the struct it's self, which can be used anywhere.

I imagine `struct/` folder as one repository where the utility functions of structs live, not hidden away in folders that only  have the first use of the struct.

Consider `t_cmd` it's used in execution and defined there, but the first time it's used is by the parser, do we now have to move the code that defines the struct and it's utility functions to parsing. What if in the future we change our mind. It makes more sense to separate this from task specific code. 

That said I agree it's maybe a bit much to have it all in one file, so maybe it's better to:

```
structs/
    t_token.c
    t_tree.c
    t_word_lst.c
    t_cmd.c
    t_redir.c
    t_cmd_info
    t_fds.c
    (...)
```

Putting this together has only strengthened my conviction, I should not have to look through evert single tile to see what `structs` exist and what functions we've coded for them.

What about unifying the struct definitions into one `structs.h`

**Comment by sophiakoulen** [comment]
Okay, I see your point. Agreed.

**Comment by znichola** [comment]
Ok, I'm motivated for this refactor, can I do a fork of the `main-flow` it's got the necessary fix to get the project to compile as well as having the up-to-date strutcs.

**Comment by znichola** [comment]
or I could merge to main then fork, idk, I think if I fork main-flow it's a bit safer.

**Comment by znichola** [comment]
comepletes with merge e84a98792e158672829ba15ce4ebc1cc8eecc9f9
