### ISSUE TITLE
"closing quotes error" - how to communicate with the parent process and stop input getting

### ISSUE THREAD

**Issue by znichola** [sophiakoulen/minishell#53]
```C
	if (single_q || double_q)
		perror("closing quotes error");
```

**Comment by sophiakoulen** [comment]
The tokenizer should return an integer value of 0 if success, -2 of failure. (Or set a parameter to indicate error.).
Also, the printer should not use perror since perror prints errno.
More something like "syntax error: expecting closing quote before token `newline'", something fancy and smart.
