### ISSUE TITLE
Environment variables - optional additions

### ISSUE THREAD

**Issue by sophiakoulen** [sophiakoulen/minishell#63]
Maybe we should increment SHLVL when starting the shell.
Should we distinguish between interactive and non-interactive then? We should do some tests.

**Comment by sophiakoulen** [comment]
"When Bash invokes an external command, the variable ‘$_’ is set to the full pathname of the command and passed to that command in its environment. " extract from [bash manual](https://www.gnu.org/software/bash/manual/html_node/Environment.html).

**Comment by znichola** [comment]
`SHLVL` is incramented `$_` is too complicated
