### ISSUE TITLE
wierd quote behaviour with env

### ISSUE THREAD

**Issue by znichola** [sophiakoulen/minishell#64]
```
bash-3.2$ export U1='hello"world'
bash-3.2$ env | grep U1
U1=hello"world
bash-3.2$

bash-3.2$ export U2="'hello world'"
bash-3.2$ env | grep U2
U2='hello world'
bash-3.2$

bash-3.2$ export U3='"hello world"'
bash-3.2$ env | grep U3
U3="hello world"
bash-3.2$

bash-3.2$ export U4='hello world'
bash-3.2$ <U4
bash: U4: No such file or directory
bash-3.2$ <$U4
bash: $U4: ambiguous redirect
bash-3.2$ export U4='hello "world'
bash-3.2$ <$U4
bash: $U4: ambiguous redirect
bash-3.2$ export U5='"world'
bash-3.2$ <$U5
bash: "world: No such file or directory
bash-3.2$
```

This I suspect is bash playing tricks on us, I think the string stored in env is not "bare" as they present, but rather the quote information is preserved and to display they omit the outer most quotes. 

Even if it's not how they do it, it would solve our problem, I think.

If we record `export U1='hello"world'` as `'hello"world'` then when it comes to replacement we will know that what's inside is not to be touched, and if the string is copies as is with the single quotes the quote removal phase will remove them and present the correct string.

and if we record `export U2="hello world"` as `"hello world"` but when we replace we only put `hello world` with no quotes. The field splitting can be properly preformed and will produce two words.

When we read env we look at the quote information in each entry, if there is a `"` then we know that the string is really a single quote string. 

This does not quite work, we still need to split around the whitespaces in single quotes, but keep any `"` characters within. 

Maybe bash tokenizes env when it recordes a value? Then it will know what should be two spaces and which quote characters need to be saved. Idk.

**Comment by znichola** [comment]
Thinking about it about it, maybe we should store the resulting strings from param expansion as tokens that record if they come from variable expansion.

**Comment by znichola** [comment]
upon farther reflection I think maybe, the way bash preserves the quotes that come from env, is to record them as escaped characters `\"` or `\'`. On recording the env these backslashes would need to be added to any lone quote characters, thus when it comes time to remove excess quotes after replacement these are not touched and remain in place. Pairs of quoted characters would however be recorded as is, this ensures they get printed and will protect the characters they enclose.

All in all this would requite a change to the` quote_removal()` to be sensitive to a backslash before a quote and ignore it when it comes to figuring out if we are in or outside a quote.

**Comment by t-h2o** [comment]
Good luck, I hope that will help you !

```bash
bash-3.2$ export U6='"hello world"'
bash-3.2$ for word in $U6; do echo "->" $word; done
-> "hello
-> world"
bash-3.2$ for word in \"hello\ world\" ; do echo "->" $word; done
-> "hello world"
bash-3.2$ for word in \"hello world\" ; do echo "->" $word; done
-> "hello
-> world"
bash-3.2$ for word in "$U6"; do echo "->" $word; done
-> "hello world"
bash-3.2$ for word in "${U6}"; do echo "->" $word; done
-> "hello world"
bash-3.2$ 
```
