### ISSUE TITLE
Quote removal to respect escaped `" '` and `\`

### ISSUE THREAD

**Issue by znichola** [sophiakoulen/minishell#82]
This is important to have the correct behaviour

**Comment by sophiakoulen** [comment]
working on it

**Comment by sophiakoulen** [comment]
Achieved with b0059301d7514e3530ad159a3d1950c734af150c
We can now have special characters in variable values, and backslashes work like in bash.
The code for param_expansion has gotten quite ugly though and too long.
I believe that now that escaping is possible also in the param_expansion phase, it could be best to use something similar to what i did in quite_removal2: loop over the whole string and keep track of a state which will affect the way we treat characters.
