### ISSUE TITLE
exit printing "exit" when in pipe

### ISSUE THREAD

**Issue by znichola** [sophiakoulen/minishell#83]
``` bash
minishell:
minishell$ ls | exit 13
exit
minishell$

bash:
bash-3.2$ ls | exit 13
bash-3.2$
```

**Comment by sophiakoulen** [comment]
And also should not print exit in non-interactive mode

**Comment by sophiakoulen** [comment]
This one might be painful to solve

**Comment by znichola** [comment]
Yes, I was thinking about it, and we would need information on if we're in a fork or not, and currently we don't have this, I think our global would need to become a struct, with the return value and the process pid.

**Comment by znichola** [comment]
Or at the moment we execute, we pass exit some information to tell it we are in a pipe. 

...

or we just make a new exit fucntion, and in execute built-in we switch to the no print exit for a pipeline

**Comment by znichola** [comment]
We have come up with multiple solutions, non quite click with satisfaction. 

- modify a global environment to indicate if it's a child or not, but our allotted global is taken up by `SIGINT` handler. 
- wrapper for exit, to make two exits, one that prints one that doesn't, but this is very in-elegant.
- modify an environment variable, and the main process reads it to check if exit should be printed, what if the user also modifies this env variable? 
...
