### ISSUE TITLE
e_string token changes

### ISSUE THREAD

**Issue by znichola** [sophiakoulen/minishell#9]
These characters: `'`, `"` need to be respected.

White spaces and the start and end of a string should be trimmed, they change nothing right?
This would remove white space string that just pollute the token list.

**Comment by sophiakoulen** [comment]
Yes, the tokenization needs do some word splitting. Thing is, later there will be more word splitting. So confusing!

**Comment by znichola** [comment]
sort of solved and it's moved to  #36
